# frozen_string_literal: true

require 'rubocop'
require_relative 'rubocop-performance/version'

require_relative 'rubocop/cop/performance/caller'
require_relative 'rubocop/cop/performance/case_when_splat'
require_relative 'rubocop/cop/performance/casecmp'
require_relative 'rubocop/cop/performance/count'
require_relative 'rubocop/cop/performance/detect'
require_relative 'rubocop/cop/performance/double_start_end_with'
require_relative 'rubocop/cop/performance/end_with'
require_relative 'rubocop/cop/performance/fixed_size'
require_relative 'rubocop/cop/performance/flat_map'
require_relative 'rubocop/cop/performance/inefficient_hash_search'
require_relative 'rubocop/cop/performance/lstrip_rstrip'
require_relative 'rubocop/cop/performance/range_include'
require_relative 'rubocop/cop/performance/redundant_block_call'
require_relative 'rubocop/cop/performance/redundant_match'
require_relative 'rubocop/cop/performance/redundant_merge'
require_relative 'rubocop/cop/performance/redundant_sort_by'
require_relative 'rubocop/cop/performance/regexp_match'
require_relative 'rubocop/cop/performance/reverse_each'
require_relative 'rubocop/cop/performance/sample'
require_relative 'rubocop/cop/performance/size'
require_relative 'rubocop/cop/performance/compare_with_block'
require_relative 'rubocop/cop/performance/start_with'
require_relative 'rubocop/cop/performance/string_replacement'
require_relative 'rubocop/cop/performance/times_map'
require_relative 'rubocop/cop/performance/unfreeze_string'
require_relative 'rubocop/cop/performance/unneeded_sort'
require_relative 'rubocop/cop/performance/uri_default_parser'

